language: ruby

rvm:
  - 2.0.0-p481

env:
  - RAILS_ENV=test

script:
  - grunt jshint
  - RAILS_ENV=test bundle exec rake spec:javascript

before_script:
  - npm install
  - bundle exec rake bower:install:development
  - cp config/application.yml.example config/application.yml